# -*- coding: utf-8 -*-
"""day13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_qXopcpbLd5nAuNLqs5IjM3Wa8mG2eO
"""

import numpy as np
import pandas as pd

df =pd.read_csv('/content/placement.csv')

df.head()

df.shape

df.info()

df = df.iloc[:,1:]

import matplotlib.pyplot as plt

plt.scatter(df['cgpa'],df['iq'],c=df['placement'])

x = df.iloc[:,0:2]
y = df.iloc[:,-1]

x

y.shape

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1)

x_test

y_test

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

x_test

x_train

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

# Model Trainin
clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

print("Train accuracy:", accuracy_score(y_train, clf.predict(x_train)))
print("Test accuracy :", accuracy_score(y_test, clf.predict(x_test)))

from sklearn.model_selection import cross_val_score

scores = cross_val_score(clf, x, y, cv=10)
print(scores)
print("Mean accuracy:", scores.mean())

from mlxtend.plotting import plot_decision_regions
plot_decision_regions(x_train,y_train.values, clf=clf, legend=2)

import pickle

pickle.dump(clf,open('model.pkl','wb'))