# -*- coding: utf-8 -*-
"""day11.ipynb

Automatically generated by Colab.


"""

import numpy as np

a = np.array(4)

a


a.ndim

arr = np.array([1, 2, 3, 4, 5])

arr.ndim

mat =np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],])

mat

mat.ndim